# Generated by Django 5.0.2 on 2024-12-02 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('edition_id', models.AutoField(primary_key=True, serialize=False)),
                ('edition_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeRegistration',
            fields=[
                ('time_registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_registration_start', models.DateTimeField()),
                ('time_registration_end', models.DateTimeField()),
                ('time_registration_day', models.IntegerField()),
                ('time_registration_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collectie.edition')),
            ],
        ),
    ]
