# Generated by Django 5.0.2 on 2024-12-02 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('bank_account', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('BTW_number', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='participating_club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_in_charge_day1', models.CharField(max_length=100)),
                ('person_in_charge_day2', models.CharField(max_length=100)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collectie.club')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collectie.edition')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('day', models.IntegerField()),
                ('volunteers_required', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('responsible_employee', models.CharField(max_length=100)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collectie.edition')),
                ('participating_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collectie.participating_club')),
            ],
        ),
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('size', models.ManyToManyField(to='data_collectie.size')),
            ],
        ),
        migrations.CreateModel(
            name='availableTshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collectie.edition')),
                ('tshirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collectie.tshirt')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_registry_number', models.CharField(max_length=100)),
                ('works_day1', models.BooleanField()),
                ('works_day2', models.BooleanField()),
                ('needs_parking_day1', models.BooleanField()),
                ('needs_parking_day2', models.BooleanField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collectie.club')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collectie.size')),
                ('tshirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collectie.availabletshirt')),
            ],
        ),
        migrations.CreateModel(
            name='TimeRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.IntegerField()),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collectie.edition')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collectie.volunteer')),
            ],
        ),
    ]
