# Generated by Django 5.0.2 on 2024-12-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collectie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participatingclub',
            name='person1_in_charge_day1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participatingclub',
            name='person1_in_charge_day2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participatingclub',
            name='person_in_charge_day1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participatingclub',
            name='person_in_charge_day2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
