# Generated by Django 5.1.4 on 2024-12-27 11:18

from django.db import migrations, models

def create_current_edition(apps, schema_editor):
    # Get the Edition model from the historical version of the app
    Edition = apps.get_model('data_collectie', 'Edition')
    
    # Optionally, set all existing editions' isCurrentEdition to False
    Edition.objects.filter(isCurrentEdition=True).update(isCurrentEdition=False)
    
    # Create a new Edition with isCurrentEdition=True
    Edition.objects.create(year=2025, isCurrentEdition=True)

class Migration(migrations.Migration):

    dependencies = [
        ('data_collectie', '0004_alter_availabletshirt_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='isCurrentEdition',
            field=models.BooleanField(default=False),
        ),
        # Add custom Python code to create the current edition
        migrations.RunPython(create_current_edition),
    ]
