# Generated by Django 5.1.4 on 2025-01-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collectie', '0005_edition_iscurrentedition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeregistration',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timeregistration',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
