version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: custom-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "gladio"
      MYSQL_USER: "gladioforce"
      MYSQL_PASSWORD: "gladioforce"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: