name: CI/CD Pipeline to destroy GladioForce Production Environment in AWS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Production
        required: true
        default: Production

jobs:
production-destroy:
    name: Destroy Production Environment
    runs-on: ubuntu-latest
    steps:

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}


      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./deploy

      - name: Destroy Terraform Environment
        run: |
          export TF_VAR_ecr_image_api=${{ secrets.ECR_REPO }}:${{ github.sha }}
          terraform destroy -var-file="00-project.tfvars" -auto-approve
        working-directory: ./deploy